/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ipproject14;

import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;

import javax.swing.JOptionPane;

import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author talina06
 */
public class Welcome extends javax.swing.JFrame {
String password="";
String username="";
String port="";

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
            
    }public void close(){WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 600));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setText(" Please Enter Your MYSQL Username and Password :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(420, 400, 530, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(660, 440, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username ('root' by default):");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(420, 440, 220, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Password ('root' by default):");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(420, 470, 220, 17);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(660, 470, 120, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(660, 500, 120, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("DONE");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(810, 440, 80, 90);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Port('3306' by default):");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(420, 500, 210, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproject14/chemistry-woman.jpg"))); // NOI18N
        jLabel1.setText("knfvjkdfbvd");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 570);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        password=new String(jPasswordField1.getPassword());
/**
 * the getText method can also be used for a password field only that its a decrepitated method
 *hence the horizontal scratch!!
  */
      //  password=jPasswordField1.getText();<- method decrepitated.
       username=jTextField1.getText();
       port=jTextField2.getText();
         boolean check_database=false,user_permission=false;
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:"+port+"/",username,password);
            Statement stmt=(Statement)con.createStatement();
            try
            {
            stmt.execute("create database myp;");
            stmt.execute("use myp;");
            stmt.execute("create table p_t(Description varchar(50), H varchar(50), He varchar(50), Li varchar(50), Be varchar(50), B varchar(50),  C varchar(50), N varchar(50), O varchar(50), F varchar(50), Ne varchar(50), Na varchar(50), Mg varchar(50), Al varchar(50), Si varchar(50), P varchar(50),S varchar(50), Cl varchar(50), Ar varchar(50), K varchar(50), Ca varchar(50), Sc varchar(50), Ti varchar(50), V varchar(50), Cr varchar(50), Mn varchar(50), Fe varchar(50), Co varchar(50), Ni varchar(50), Cu varchar(50), Zn varchar(50), Ga varchar(50), Ge varchar(50), Ast varchar(50), Se varchar(50), Br varchar(50), Kr varchar(50), Rb varchar(50), Sr varchar(50), Y varchar(50), Zr varchar(50), Nb varchar(50), Mo varchar(50), Tc varchar(50), Ru varchar(50), Rh varchar(50), Pd varchar(50), Ag varchar(50), Cd varchar(50), Ind varchar(50), Sn varchar(50), Sb varchar(50), Te varchar(50), I varchar(50), Xe varchar(50), Cs varchar(50), Ba varchar(50), La varchar(50), Ce varchar(50), Pr varchar(50),Nd varchar(100),Pm  varchar(100),Sm varchar(100),Eu varchar(100),Gd varchar(100),Tb varchar(100),Dy varchar(100),Ho varchar(100),Er varchar(100),Tm varchar(100), Yb varchar(100),Lu varchar(100),Hf varchar(100),Ta varchar(100),W varchar(100),Re varchar(100),Os varchar(100),Ir varchar(100),Pt varchar(100),Au varchar(100),Hg varchar(100),Tl varchar(100),Pb varchar(100),Bi varchar(100),Po varchar(100),At varchar(100),Rn varchar(100),Fr varchar(100),Ra varchar(100),Ac varchar(100),Th varchar(100),Pa varchar(100),U varchar(100),Np varchar(100),Pu varchar(100),Am varchar(100),Cm varchar(100),Bk varchar(100),Cf varchar(100),Es varchar(100),Fm varchar(100),Md varchar(100),No varchar(100),Lr varchar(100),Rf varchar(100),Db varchar(100),Sg varchar(100),Bh varchar(100),Hs varchar(100),Mt varchar(100),Ds varchar(100),Rg varchar(100),Cn varchar(100),Uut varchar(100),Fl varchar(100),Uup varchar(100),Lv varchar(100),Uus varchar(100),Uuo varchar(100));");
          
            int ask;
            ask = JOptionPane.showConfirmDialog(null,"The Periodic Table database does not exist. Do you wish to allow the program to create the database in MYSQL?");
            if (ask == JOptionPane.YES_OPTION)
            {
            user_permission=true;
            JOptionPane.showMessageDialog(null,"The database shall now be created. This process will take a while. Please wait after clicking OK.");
            }
            else
            {
            stmt.execute("drop database myp;");
            }
            }
            catch(Exception e) {
            check_database=true;          
            }
        if((check_database==false)&&(user_permission==true)){ 
          String query1="insert into p_t values('Latin_name','Hydrogenium', 'Helium', 'Lithium', 'Beryllium', 'Borum', 'Carboneum', 'Nitrogenium', 'Oxygenium', 'Fluorum', 'Neon', 'Natrium', 'Magnesium', 'Aluminium', 'Silicium', 'Phosphorus', 'Sulfur', 'Chlorum', 'Argon', 'Kalium', 'Calcium', 'Scandium', 'Titanium', 'Vanadium', 'Chromium', 'Manganum', 'Ferrum', 'Cobaltum', 'Niccolum', 'Cuprum', 'Zincum', 'Gallium', 'Germanium', 'Arsenicum', 'Selenium', 'Bromum', 'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium', 'Niobium', 'Molybdaenum', 'Technetium', 'Ruthenium', 'Rhodium', 'Palladium', 'Argentum', 'Cadmium', 'Indium', 'Stannum', 'Stibium', 'Tellurium', 'Iodum', 'Xenon', 'Caesium', 'Barium', 'Lanthanum', 'Cerium', 'Praseodymium','Neodymium','Promethium','Samarium','Europium','Gadolinium','Terbium','Dysprosium','Holmium','Erbium','Thulium','Ytterbium','Lutetium','Hafnium','Tantalum','Wolframium','Rhenium','Osmium','Iridium','Platinum','Aurul','Hydrargyrum','Thallium','Plumbum','Bismuthum','Polonium','Astetium','Radon','Francium','Radium','Actinium','Thorium','Protactinium','Uranium','Neptunium','Plutonium','Americium','Curium','Berkilium','Caloifornium','Einsteinium','Fermium','Modelivium','Nobelium','Lowrencim','Rutherfordium','Dubnium','Ceaborgium','Bhorium','Hassium','Meitnerium','Darmstadtium','Roentgenium','Copernicum','Ununtrium','Flerovium','Ununpentium','Livermorium','Ununseptium','Ununoctium');";
         stmt.executeUpdate(query1);
          String query2="insert into p_t values('Discovery year','1766', '1895', '1817', '1797', '1808', 'Prehistoric', '1772', '1774', '1886', '1898', '1807', '1755', '1825', '1824', '1669', '500 BC', '1774', '1894', '1807', '1808', '1879', '1791', '1801', '1797', '1774', '2000 BC', '1735', '1751', '8000 BC', '1500', '1875', '1886', '1250', '1817', '1826', '1898', '1861', '1790', '1794', '1789', '1801', '1781', '1937', '1844', '1803', '1803', '3000 BC', '1817', '1863', '3000 BC', '3000 BC', '1783', '1811', '1898', '1860', '1808', '1839', '1803', '1885','1885','1945','1879','1901','1880','1843','1886','1878','1842','1879','1878','1907', '1923','1802','1783','1925','1803','1803','1735','2500BC','1500BC','1861','4000BC','1400','1898','1940','1900','1939','1898','1899','1829','1913','1789','1940','1940','1944','1944','1949','1950','1952','1952','1955','1958','1961','1964','1967','1974','1981','1984','1982','1994', '1994','1996','2004','1998','2004','2000','2010','2006');";
         stmt.executeUpdate(query2);
       String query3="insert into p_t values('AtomicWeight','1.00794', '4.002602', '6.941', '9.012182', '10.811', '12.0107', '14.0067', '15.9994', '18.9984032', '20.1797', '22.98976928', '24.3050', '26.9815386', '28.0855', '30.973762', '32.065', '35.453', '39.948', '39.0983', '40.078', '44.955912', '47.867', '50.9415', '51.9961', '54.938045', '55.845', '58.933195', '58.6934', '63.546', '65.38', '69.723', '72.64', '74.92160', '78.96', '79.904', '83.798', '85.4678', '87.62', '88.90585', '91.224', '92.90638', '95.96', '97.9072', '101.07', '102.90550', '106.42', '107.8682', '112.411', '114.818', '118.710', '121.760', '127.60', '126.90447', '131.293', '132.9054519', '137.327', '138.90547', '140.116', '140.90765','144.242','145','150.36','151.964','157.25','158.925','162.5','164.93','167.25','168.934','173','174','178.49','180.94788','183.84','186.207','190.23','192.217','195.084','196.966569','200.59','204.3833','207.2','208.98040','208.9824','209.9871','222.0176','223','226','227','232.03806','231.03588','238.02891','237','244','243','247','247','251','252','257','258','259','262','261','262','266','264','277','268','271','272','285','284','289','288','292','294','294');";
          stmt.executeUpdate(query3);
          String query4="insert into p_t values('Covalent Radius','37', '32', '134', '90', '82', '77', '75', '73', '71', '69', '154', '130', '118', '111', '106', '102', '99', '97', '196', '174', '144', '136','125', '127', '139', '125', '126', '121', '138', '131','126', '122', '119', '116', '114', '110', '211', '192', '162', '148', '137', '145', '156', '126', '135', '131', '153', '148', '144', '141', '138', '135', '133', '130', '225', '198','169', 'null' ,'null','null','null','null','null','null','null','null','null','null','null','null','160', '150','138','146','159','128','137','128','144','149','148','147','146','null','null','145','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null');";
        stmt.executeUpdate(query4);
          String query5="insert into p_t values('Phase', 'gas', 'gas','solid', 'solid', 'solid', 'solid', 'gas', 'gas', 'gas', 'gas', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'gas', 'gas', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'liquid', 'gas', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'solid', 'gas', 'solid', 'solid', 'solid', 'solid', 'solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','liquid','solid','solid','solid','solid','solid','gas','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','solid','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null');";
        stmt.executeUpdate(query5);
          String query6="insert into p_t values('Specific Heat', '14300', '5193.1', '3570', '1820', '1030', '710', '1040', '919', '824', '1030', '1230', '1020', '904', '710', '769.7', '705', '478.2', '520.33', '757', '631', '567', '520', '489', '448', '479', '449', '421', '445', '384.4', '388', '371', '321.4', '328', '321.2', '947.3', '248.5', '364', '300', '298', '278', '265', '251', '63', '238', '240', '240', '235', '240', '233', '217', '207', '201', '429', '158.32', '242', '205', '195', '192', '193','190','null','196','182','240','182','167','165','168','160','154','154','144','140','132','137','130','131','133','129.1','139.5','129','127','122','null','null','93.65','null','92','120','118','99.1','116','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null');";
         stmt.executeUpdate(query6);
          String query7="insert into p_t values('color', 'colorless', 'colorless', 'silver', 'slate gray', 'black', 'black', 'colorless', 'colorless', 'colorless', 'colorless', 'silver', 'silver', 'silver', 'gray', 'colorless', 'yellow', 'yellow', 'colorless', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'gray', 'gray', 'gray', 'copper', 'slate gray', 'silver', 'gray', 'silver', 'gray', 'red', 'colorless', 'silver', 'silver', 'silver', 'silver', 'silver', 'gray', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'silver', 'slate gray', 'colorless', 'silver', 'silver', 'silver', 'silver', 'silver','silver','silver','silver','silver','silver','silver','silver','silver','silver','silver','silver','silver','gray','gray','gray','gray','slategray',      'silver','gray','gold','silver','silver','slategray','gray','silver','silver','colouress','silver','silver','silver','silver','silver','silver','silver','silver', 'silver', 'silver','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null','null' );";
        stmt.executeUpdate(query7);
          String query8="insert into p_t values('Valence','1', '0', '1', '2', '3', '4', '3', '2', '1', '0', '1', '2', '3', '4', '5', '6', '1', '0', '1', '2', '3', '4', '5', '6', '4', '3', '4', '2', '2', '2', '3', '4', '5', '6', '7', '2', '1', '2', '3', '4', '5', '6', '7', '6', '6', '4', '1', '2', '3', '4', '5', '6', '7', '6', '1', '2', '3','4', '4','3','3','3','3','3','3','3','3','3','3','3','3','4','5','6','7','6','6','6','5','2','3','4','5','6','7','6','3','2','3','4','5','6','6','6','4','4','4','4','4','3','3','3','3','4','5','6','7','null','null','null','null','null','null','null','null','null','null','null' );";
         stmt.executeUpdate(query8);
          String query9=" insert into p_t values('Radioactive','no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes','yes' );";
        stmt.executeUpdate(query9);
          String query10="insert into p_t values('Block', 's', 's', 's', 's', 'p', 'p', 'p', 'p', 'p', 'p', 's', 's', 'p', 'p', 'p', 'p', 'p', 'p', 's', 's', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'p', 'p', 'p', 'p', 'p', 'p', 's', 's', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'p', 'p', 'p', 'p', 'p', 'p', 's', 's', 'f', 'f','f','f','f','f','f','f','f','f','f','f','f','f','f','d','d','d','d','d','d','d','d','d','p','p','p','p','p','p','s','s','f','f','f','f','f','f','f','f','f','f','f','f','f','f','f','d','d','d','d','d','d','d','d','d','p','p','p','p','p','p' );";
        stmt.executeUpdate(query10);
        }check_database=true;
            JOptionPane.showMessageDialog(null,"Congratulations!Your periodic table has been successfully created.");
            }
        catch(Exception e)
        { 
            JOptionPane.showMessageDialog(null,"The username or password you have entered is incorrect. Please check them. Also,do check for any spaces you may have left accidentally.");
        }
        if(check_database==true){new projectip().setVisible(true);
                                    close();}
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public static final javax.swing.JPasswordField jPasswordField1 = new javax.swing.JPasswordField();
    public static final javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField jTextField2 = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
